# **Topic Modelling**

## Dataset

link youtube https://www.youtube.com/watch?v=DgdOQe4aQwU

In [1]:
import pandas as pd
from googleapiclient.discovery import build

In [2]:
def video_comments(video_id):
    # empty list for storing reply
    replies = []

    # creating youtube resource object
    youtube = build('youtube', 'v3', developerKey=api_key)

    # retrieve youtube video results
    video_response = youtube.commentThreads().list(part='snippet,replies', videoId=video_id).execute()

    # iterate video response
    while video_response:
        
        # extracting required info
        # from each result object
        for item in video_response['items']:
            
            # Extracting comments ()
            published = item['snippet']['topLevelComment']['snippet']['publishedAt']
            user = item['snippet']['topLevelComment']['snippet']['authorDisplayName']

            # Extracting comments
            comment = item['snippet']['topLevelComment']['snippet']['textDisplay']
            likeCount = item['snippet']['topLevelComment']['snippet']['likeCount']

            replies.append([published, user, comment, likeCount])
            
            # counting number of reply of comment
            replycount = item['snippet']['totalReplyCount']

            # if reply is there
            if replycount>0:
                # iterate through all reply
                for reply in item['replies']['comments']:
                    
                    # Extract reply
                    published = reply['snippet']['publishedAt']
                    user = reply['snippet']['authorDisplayName']
                    repl = reply['snippet']['textDisplay']
                    likeCount = reply['snippet']['likeCount']
                    
                    # Store reply is list
                    #replies.append(reply)
                    replies.append([published, user, repl, likeCount])

            # print comment with list of reply
            #print(comment, replies, end = '\n\n')

            # empty reply list
            #replies = []

        # Again repeat
        if 'nextPageToken' in video_response:
            video_response = youtube.commentThreads().list(
                    part = 'snippet,replies',
                    pageToken = video_response['nextPageToken'], 
                    videoId = video_id
                ).execute()
        else:
            break
    #endwhile
    return replies

In [3]:
api_key = 'AIzaSyD6Lb7fJBcMcxcvKsIRctUXv_bwTyxc56w' 
# url = https://www.youtube.com/watch?v=DgdOQe4aQwU
video_id = "DgdOQe4aQwU" #id video
# Call function
comments = video_comments(video_id)
comments

[['2023-05-26T16:59:49Z',
  'Suhut Maulanaibrahim',
  'Biar nantinya kalau ada dibilang kecurangan biar Mana buktinya mana faktanya mana ininya sekarang harus jujur dan adil harus pemilihan secara sehat dan juga terbuka harus dihitung di daerah kalau dihitung di daerah Insya Allah nggak bakalan ada kecurangan biar masyarakat yang jadi saksi kalau nggak dijaga misalnya TNI Polri ada atau dan lain sebagainya biar masyarakat yang menyaksiin sendiri kalau bisa semuanya syuting atau videoin biar terlihat jelas kalau bisa sekarang ini secara transparan secara terbuka terus harus publik harus tahu semua sekarang nggak ada yang ditutup-tutupin kalau ada yang kalau ada yang ditutup tutupin Seujung rambut saja pasti dia punya niat yang nggak baik punya niat buruk tentunya Nggak meleset dari situ pasti kalau ditutupin itu punya rencana buruk dan tidak baik mengajukan pilihan tersebut yang hasilnya murni dari masyarakat mau ngajak-ngajak keadaan mau bikin kalang kabut keadaan mau bikin Terus mau b

In [4]:
df = pd.DataFrame(comments, columns=['publishedAt', 'authorDisplayName', 'textDisplay', 'likeCount'])
df

publishedAt              authorDisplayName  \
0   2023-05-26T16:59:49Z           Suhut Maulanaibrahim   
1   2023-05-26T16:56:14Z           Suhut Maulanaibrahim   
2   2023-05-26T16:54:01Z           Suhut Maulanaibrahim   
3   2023-05-26T16:48:00Z           Suhut Maulanaibrahim   
4   2023-05-10T11:20:39Z                 david pirngadi   
5   2023-05-05T07:47:21Z                     Nurul Izza   
6   2023-05-05T07:43:42Z                     Nurul Izza   
7   2023-05-05T04:08:34Z                   izmail exact   
8   2023-05-04T18:31:41Z                    Qolis Fuadi   
9   2023-05-02T16:30:21Z           Warta Dunia Official   
10  2023-05-02T09:28:42Z                  Pekak Ajusszz   
11  2023-04-30T23:35:35Z                    WAN RAHMADI   
12  2023-04-30T15:17:37Z               APTA  HOBI JOGET   
13  2023-04-30T14:45:52Z                      Den Dayen   
14  2023-04-29T08:56:57Z                  Riana Cecilia   
15  2023-04-29T08:33:15Z                  Ahmad Baidawi   
16  2023-04-29T07:02:21Z                     Ahmad Dewi   
17  2023-05-08T14:06:25Z                    Dana Kusuma   
18  2023-04-29T04:38:46Z       Helmi pindra Helm pindra   
19  2023-04-29T03:39:58Z                           E_NS   
20  2023-04-28T12:48:29Z                  Wibowo Wibowo   
21  2023-04-28T08:40:44Z                    Garam dapur   
22  2023-05-03T11:59:02Z                 Wandi.setiawan   
23  2023-04-29T03:31:50Z                     James Bond   
24  2023-04-28T08:36:23Z              romansa kehidupan   
25  2023-04-28T08:35:03Z              romansa kehidupan   
26  2023-05-02T19:55:27Z             Andrea Jussienando   
27  2023-04-28T08:24:34Z                        Ph Oppo   
28  2023-04-28T07:53:35Z          MD SUARA RAKYAT TOLIS   
29  2023-05-08T14:07:33Z                    Dana Kusuma   
30  2023-04-28T13:27:56Z          MD SUARA RAKYAT TOLIS   
31  2023-04-28T08:35:02Z                       cukufalu   
32  2023-04-28T07:48:18Z                  lambe turahan   
33  2023-04-30T13:54:24Z                  lambe turahan   
34  2023-04-30T13:50:02Z                  lambe turahan   
35  2023-04-30T13:40:12Z                    Hanrecovery   
36  2023-04-30T09:00:22Z                  lambe turahan   
37  2023-04-30T07:33:58Z                    Hanrecovery   
38  2023-04-28T07:46:35Z                     husnedi 01   
39  2023-04-28T07:44:31Z              Dara sabila Putri   
40  2023-04-28T07:41:10Z                     Mhd Syukur   
41  2023-04-28T07:20:22Z                  Adiyanto Amri   
42  2023-04-28T07:10:08Z                      Ali Utomo   
43  2023-04-28T07:09:00Z         Chusu inspirator negri   
44  2023-05-09T09:18:10Z  Juanda Ottodinata Linggabuana   
45  2023-04-29T03:51:36Z         Chusu inspirator negri   
46  2023-04-29T03:37:56Z                     James Bond   
47  2023-04-28T10:39:55Z                       Alamsyah   
48  2023-04-28T10:36:07Z         Chusu inspirator negri   
49  2023-04-28T07:06:36Z            Fahluzy76 Fahluzy76   
50  2023-04-28T07:04:35Z                Subagio Subagio   
51  2023-05-03T15:32:32Z                  lambe turahan   
52  2023-05-03T03:09:02Z                   Pangat Bador   
53  2023-04-30T13:56:25Z                  lambe turahan   
54  2023-04-28T06:51:38Z                   Vicky Andrea   
55  2023-04-28T07:20:38Z            Sohibandi Sohibandi   
56  2023-04-28T07:08:12Z                      Duni Duni   

                                          textDisplay  likeCount  
0   Biar nantinya kalau ada dibilang kecurangan bi...          0  
1   Pilihan secara sehat terbuka judul jujur adil ...          0  
2   Nggak apa-apa sebagai orang Indonesia mulai da...          0  
3   Kenapa orang calon Presiden di seluruh Indones...          0  
4   Poros Baru andalah :<br>1. Mayor AHY - Anas Ur...          1  
5   Yg lebih yakin menangx,,, seandainya pak Prabo...          0  
6   Ya,,, pasti diusahakan lebih dari 2 pasang cap...          0  
7                                           Mahfud MD 

In [5]:
df.to_csv("capres2024.csv",index=False)

## Preprocessing

In [6]:
!pip install Sastrawi

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [7]:
import pandas as pd
import numpy as np
from nltk.corpus import stopwords
import re
import nltk
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('punkt')
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory
from nltk.tokenize import sent_tokenize, word_tokenize
from sklearn.feature_extraction.text import TfidfVectorizer

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [8]:
dt = pd.read_csv("capres2024.csv")


In [9]:
dt.head

<bound method NDFrame.head of              publishedAt              authorDisplayName  \
0   2023-05-26T16:59:49Z           Suhut Maulanaibrahim   
1   2023-05-26T16:56:14Z           Suhut Maulanaibrahim   
2   2023-05-26T16:54:01Z           Suhut Maulanaibrahim   
3   2023-05-26T16:48:00Z           Suhut Maulanaibrahim   
4   2023-05-10T11:20:39Z                 david pirngadi   
5   2023-05-05T07:47:21Z                     Nurul Izza   
6   2023-05-05T07:43:42Z                     Nurul Izza   
7   2023-05-05T04:08:34Z                   izmail exact   
8   2023-05-04T18:31:41Z                    Qolis Fuadi   
9   2023-05-02T16:30:21Z           Warta Dunia Official   
10  2023-05-02T09:28:42Z                  Pekak Ajusszz   
11  2023-04-30T23:35:35Z                    WAN RAHMADI   
12  2023-04-30T15:17:37Z               APTA  HOBI JOGET   
13  2023-04-30T14:45:52Z                      Den Dayen   
14  2023-04-29T08:56:57Z                  Riana Cecilia   
15  2023-04-29T08:33:15Z  

In [10]:
#cleaningtext
clean_tag = re.compile('@\S+')
clean_url = re.compile('https?:\/\/.*[\r\n]*')
clean_hastag = re.compile('#\S+')
clean_symbol = re.compile('[^a-zA-Z]')
def clean_punct(text):
    text = clean_tag.sub('', text)
    text = clean_url.sub('', text)
    text = clean_hastag.sub(' ', text)
    text = clean_symbol.sub(' ', text)
    return text
# Buat kolom tambahan untuk data description setelah dilakukan clean 
preproces= dt['textDisplay'].apply(clean_punct)
dt_clean=pd.DataFrame(preproces)
dt_clean

textDisplay
0   Biar nantinya kalau ada dibilang kecurangan bi...
1   Pilihan secara sehat terbuka judul jujur adil ...
2   Nggak apa apa sebagai orang Indonesia mulai da...
3   Kenapa orang calon Presiden di seluruh Indones...
4   Poros Baru andalah   br    Mayor AHY   Anas Ur...
5   Yg lebih yakin menangx    seandainya pak Prabo...
6   Ya    pasti diusahakan lebih dari   pasang cap...
7                                           Mahfud MD
8                        ANIES  amp  ERICK   SEMPURNA
9   Media dan pengamat di bodohi dan di bohongi ol...
10  Masukan aja   ini NKRI dari sabang sampai Mera...
11  Semoga presiden berikutnya mau menyedekahkan h...
12                              Mahfud ahok indpenden
13  kalau TGB di surve baru kita percaya   memg ke...
14  Sy sangat setuju lebih banyak capres cawapres ...
15  Yaa mau poros apapun pak prabowo tetap setia p...
16         Ujung ujung cuma ada   poross   Maksimal  
17  Msh yakin yg maju pilpres hanya   poros     lo...
18                        Anis rk nasdem pks demokrat
19  Pak Anies Rasyid Baswedan Dan Pak Agus Harimur...
20  SAYA AKAN SANGAT SENANG JIKA YOHANES GAGAL NYA...
21  Golkar harus berani mandiri jangan jadi pengek...
22                                               GPRK
23  Aerlangga cak imin vs prabowo erik vs ganjar s...
24  Jangan biarkan pelangar Ham berat memimpin neg...
25  Cuma aniss sang satrioo paningit yg akan memba...
26  Tidak ada satrio piningit dari Yaman dulu        
27                                            Bos men
28          Intinya Rakyat hanya butuh Annis baswedan
29                                                   
30   Rakyat yang mau keadilan bagi semua golongan ...
31                        Rakyat yang mana Bro       
32  poros tengah  poros terakhir biasanya pemenang...
33   Prasetyo Insani agama di gunakan untuk kepent...
34                                  ahoknya juga ogah
35    turahan dibayar pun  lembaga survey nya ogah   
36   sebab ahok gak mau membayar lembaga survey ka...
37   turahan lembaga survey pun gk bakal kepikiran...
38  Pusing amat Calonkan saja    br   Anies baswed...
39                       Ujungnya  ujungnya dua poros
40  Apapun yg ada  yg pasti partai Nasdem akhirnya...
41  Poros baru koalisi perubahan bubar dan koalisi...
42                                         poros     
43  Golkar  jadikan   poros sama pan  masih ada Ri...
44  Setuju ayo bikin   poros Ridwan Kamil   Eric T...
45                   Bond biar lebih seru klo   poros
46  Pan mengusung Erik berpasangan dg prabowo    K...
47   inspirator negri yakin pilpres aman dan menye...
48   iya hehe br Ayo bikin poros ke   br Saya mend...
49  PPP akan menyusul Hanura yg suaranya hilang di...
50  saya kira tdk ada lagi poros baru  Karena pelu...
51                                  Bador lebih parah
52                     turahan dari pada budak partai
53  jangan biarkan presiden republik indonesa jadi...
54  Siapapun capres cawapres dari lingkaran JKW  G...
55  GK NGARUH   OPI UNTUNGE TAMBAH  AWAKMU   NTAR ...
56                        Iya lah org buzzer anis

In [11]:
#lowercase
def clean_lower(lwr):
    lwr = lwr.lower() # lowercase text
    return lwr
# Buat kolom tambahan untuk data description yang telah dicasefolding  
dt_clean = dt_clean['textDisplay'].apply(clean_lower)
dt_lowecase=pd.DataFrame(dt_clean)
dt_lowecase

textDisplay
0   biar nantinya kalau ada dibilang kecurangan bi...
1   pilihan secara sehat terbuka judul jujur adil ...
2   nggak apa apa sebagai orang indonesia mulai da...
3   kenapa orang calon presiden di seluruh indones...
4   poros baru andalah   br    mayor ahy   anas ur...
5   yg lebih yakin menangx    seandainya pak prabo...
6   ya    pasti diusahakan lebih dari   pasang cap...
7                                           mahfud md
8                        anies  amp  erick   sempurna
9   media dan pengamat di bodohi dan di bohongi ol...
10  masukan aja   ini nkri dari sabang sampai mera...
11  semoga presiden berikutnya mau menyedekahkan h...
12                              mahfud ahok indpenden
13  kalau tgb di surve baru kita percaya   memg ke...
14  sy sangat setuju lebih banyak capres cawapres ...
15  yaa mau poros apapun pak prabowo tetap setia p...
16         ujung ujung cuma ada   poross   maksimal  
17  msh yakin yg maju pilpres hanya   poros     lo...
18                        anis rk nasdem pks demokrat
19  pak anies rasyid baswedan dan pak agus harimur...
20  saya akan sangat senang jika yohanes gagal nya...
21  golkar harus berani mandiri jangan jadi pengek...
22                                               gprk
23  aerlangga cak imin vs prabowo erik vs ganjar s...
24  jangan biarkan pelangar ham berat memimpin neg...
25  cuma aniss sang satrioo paningit yg akan memba...
26  tidak ada satrio piningit dari yaman dulu        
27                                            bos men
28          intinya rakyat hanya butuh annis baswedan
29                                                   
30   rakyat yang mau keadilan bagi semua golongan ...
31                        rakyat yang mana bro       
32  poros tengah  poros terakhir biasanya pemenang...
33   prasetyo insani agama di gunakan untuk kepent...
34                                  ahoknya juga ogah
35    turahan dibayar pun  lembaga survey nya ogah   
36   sebab ahok gak mau membayar lembaga survey ka...
37   turahan lembaga survey pun gk bakal kepikiran...
38  pusing amat calonkan saja    br   anies baswed...
39                       ujungnya  ujungnya dua poros
40  apapun yg ada  yg pasti partai nasdem akhirnya...
41  poros baru koalisi perubahan bubar dan koalisi...
42                                         poros     
43  golkar  jadikan   poros sama pan  masih ada ri...
44  setuju ayo bikin   poros ridwan kamil   eric t...
45                   bond biar lebih seru klo   poros
46  pan mengusung erik berpasangan dg prabowo    k...
47   inspirator negri yakin pilpres aman dan menye...
48   iya hehe br ayo bikin poros ke   br saya mend...
49  ppp akan menyusul hanura yg suaranya hilang di...
50  saya kira tdk ada lagi poros baru  karena pelu...
51                                  bador lebih parah
52                     turahan dari pada budak partai
53  jangan biarkan presiden republik indonesa jadi...
54  siapapun capres cawapres dari lingkaran jkw  g...
55  gk ngaruh   opi untunge tambah  awakmu   ntar ...
56                        iya lah org buzzer anis

In [12]:
import nltk
nltk.download('stopwords')
nltk.download('punkt')
from nltk.tokenize import sent_tokenize, word_tokenize
from nltk.corpus import stopwords

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [13]:
!pip install indoNLP

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [14]:
slang_dict = pd.read_csv("https://raw.githubusercontent.com/DwiAsfi/prosaindata/main/slank.txt", sep=" ", header=None)
from indoNLP.preprocessing import replace_slang
from indoNLP.preprocessing import replace_word_elongation
replace_slang
def replace_slang_words(text):
    words = nltk.word_tokenize(text.lower())
    words_filtered = [word for word in words if word not in stopwords.words('indonesian')]
    for i in range(len(words_filtered)):
        if words_filtered[i] in slang_dict:
            words_filtered[i] = slang_dict[words_filtered[i]]
    return ' '.join(words_filtered)

# penggunaan
dt_lowecase=[]
for i in range(len(dt_clean)):
  dt_lowecase.append(dt_clean[i])

slang_words=[]
for i in range(len(dt_lowecase)):
  slang = replace_slang_words(dt_lowecase[i])
  y=replace_slang(slang)
  slang_words.append(y)

slang = pd.DataFrame(slang_words, columns=["Slank"])
slang

Slank
0   biar dibilang kecurangan biar buktinya faktany...
1   pilihan sehat terbuka judul jujur adil sosok p...
2   enggak orang indonesia sabang merauke ditutup ...
3   orang calon presiden indonesia enggak kayak ca...
4   poros baru mayor ahy anas urbaningrum baru iba...
5   yang menangx seandainya prabowo berpasangan de...
6   ya diusahakan pasang capres memenangkan ganjar...
7                                           mahfud md
8                            anies amp erick sempurna
9   media pengamat bodohi bohongi dagelan politik ...
10  masukan saja nkri sabang meraoke cawapres indo...
11  semoga presiden menyedekahkan hartanya masyara...
12                              mahfud ahok indpenden
13  tgb surve percaya memg kenyataan safari pengaj...
14  saya setuju capres cawapres pilihan rakyat bia...
15  ya poros apapun prabowo setia bendera merah putih
16                        ujung ujung poross maksimal
17  masih yang maju pilpres poros logistik pilpres...
18                        anis rk nasdem pks demokrat
19  anies rasyid baswedan agus harimurti yudhoyono...
20  senang yohanes gagal nyapres pilpres aman dama...
21                     golkar berani mandiri pengekor
22                                               gprk
23  aerlangga cak imin vs prabowo erik vs ganjar s...
24  biarkan pelangar ham berat memimpin negriii ko...
25  aniss sang satrioo paningit yang membawa kemak...
26                              satrio piningit yaman
27                                            bos men
28                intinya rakyat butuh annis baswedan
29                                                   
30  rakyat keadilan golongan rakyat perubahan hany...
31                                         rakyat bro
32  poros poros pemenangnya baru baru seandainya s...
33  prasetyo insani agama kepentingan politik agam...
34                                       ahoknya ogah
35            turahan dibayar lembaga survey nya ogah
36  ahok enggak membayar lembaga survey kali yang ...
37  turahan lembaga survey enggak kepikiran nama a...
38  pusing calonkan baru anies baswedan baru ganja...
39                            ujungnya ujungnya poros
40  apapun yang yang partai nasdem pemerintahan pa...
41  poros koalisi perubahan bubar koalisi prabowo ...
42                                              poros
43  golkar jadikan poros kapan ridwan kamil erick ...
44  setuju ayo bikin poros ridwan kamil eric thohi...
45                          bond biar seru kalo poros
46  kapan mengusung erik berpasangan dengan prabow...
47          inspirator negeri pilpres aman menyejukan
48  iya hehe baru ayo bikin poros baru mendukung r...
49  ppp menyusul hanura yang suaranya hilang parle...
50  tidak poros peluang koalisi sudah habis koalis...
51                                        bador parah
52                               turahan budak partai
53  biarkan presiden republik indonesa petugas partai
54  capres cawapres lingkaran jkw gub palestina wo...
55  enggak ngaruh opi untunge awakmu entar tukang ...
56                              iya orang buzzer anis

In [15]:
tokenize=[]
for i in range(len(slang_words)):
  token=word_tokenize(slang_words[i])
  tokendata = []
  for x in token :
    tokendata.append(x)
  tokenize.append(tokendata)
  print(tokendata)

['biar', 'dibilang', 'kecurangan', 'biar', 'buktinya', 'faktanya', 'ininya', 'jujur', 'adil', 'pemilihan', 'sehat', 'terbuka', 'dihitung', 'daerah', 'dihitung', 'daerah', 'insya', 'allah', 'enggak', 'kecurangan', 'biar', 'masyarakat', 'saksi', 'enggak', 'dijaga', 'tni', 'polri', 'biar', 'masyarakat', 'menyaksiin', 'syuting', 'videoin', 'biar', 'transparan', 'terbuka', 'publik', 'enggak', 'ditutup', 'menutupi', 'ditutup', 'menutupi', 'seujung', 'rambut', 'niat', 'enggak', 'niat', 'buruk', 'enggak', 'meleset', 'situ', 'ditutupi', 'rencana', 'buruk', 'mengajukan', 'pilihan', 'hasilnya', 'murni', 'masyarakat', 'mengajak', 'mengajak', 'bikin', 'kalang', 'kabut', 'bikin', 'bikin', 'rusak', 'pemilihan', 'berubah', 'totalnya', 'masyarakat', 'kecewa', 'menuduh', 'menuduh', 'biar', 'biar', 'baca', 'merasakan', 'kecurangan', 'biar', 'sadar', 'enggak', 'sadar', 'enggak', 'kecurangan', 'contoh', 'buruk', 'dibawa', 'dibawa', 'mati', 'menerima', 'perbuatannya', 'keburukan', 'dibawa', 'mati', 'kebaika

In [16]:
stopword=[]
for i in range(len(tokenize)):
  listStopword =  set(stopwords.words('indonesian'))
  removed=[]
  for x in (tokenize[i]):
    if x not in listStopword:
       removed.append(x)
  stopword.append(removed)
  print(removed)

['biar', 'dibilang', 'kecurangan', 'biar', 'buktinya', 'faktanya', 'ininya', 'jujur', 'adil', 'pemilihan', 'sehat', 'terbuka', 'dihitung', 'daerah', 'dihitung', 'daerah', 'insya', 'allah', 'kecurangan', 'biar', 'masyarakat', 'saksi', 'dijaga', 'tni', 'polri', 'biar', 'masyarakat', 'menyaksiin', 'syuting', 'videoin', 'biar', 'transparan', 'terbuka', 'publik', 'ditutup', 'menutupi', 'ditutup', 'menutupi', 'seujung', 'rambut', 'niat', 'niat', 'buruk', 'meleset', 'situ', 'ditutupi', 'rencana', 'buruk', 'mengajukan', 'pilihan', 'hasilnya', 'murni', 'masyarakat', 'mengajak', 'mengajak', 'bikin', 'kalang', 'kabut', 'bikin', 'bikin', 'rusak', 'pemilihan', 'berubah', 'totalnya', 'masyarakat', 'kecewa', 'menuduh', 'menuduh', 'biar', 'biar', 'baca', 'merasakan', 'kecurangan', 'biar', 'sadar', 'sadar', 'kecurangan', 'contoh', 'buruk', 'dibawa', 'dibawa', 'mati', 'menerima', 'perbuatannya', 'keburukan', 'dibawa', 'mati', 'kebaikan', 'orang', 'membawa', 'kebaikan', 'matinya', 'berusaha']
['pilihan',

In [17]:
stemming=[]
for i in range(len(stopword)):
  factory = StemmerFactory()
  stemmer = factory.create_stemmer()
  katastem=[]
  for x in (stopword[i]):
    katastem.append(stemmer.stem(x))
  stemming.append(katastem)
  print(katastem)

['biar', 'bilang', 'curang', 'biar', 'bukti', 'fakta', 'ini', 'jujur', 'adil', 'pilih', 'sehat', 'buka', 'hitung', 'daerah', 'hitung', 'daerah', 'insya', 'allah', 'curang', 'biar', 'masyarakat', 'saksi', 'jaga', 'tni', 'polri', 'biar', 'masyarakat', 'menyaksiin', 'syuting', 'videoin', 'biar', 'transparan', 'buka', 'publik', 'tutup', 'tutup', 'tutup', 'tutup', 'ujung', 'rambut', 'niat', 'niat', 'buruk', 'meleset', 'situ', 'tutup', 'rencana', 'buruk', 'aju', 'pilih', 'hasil', 'murni', 'masyarakat', 'ajak', 'ajak', 'bikin', 'kalang', 'kabut', 'bikin', 'bikin', 'rusak', 'pilih', 'ubah', 'total', 'masyarakat', 'kecewa', 'tuduh', 'tuduh', 'biar', 'biar', 'baca', 'rasa', 'curang', 'biar', 'sadar', 'sadar', 'curang', 'contoh', 'buruk', 'bawa', 'bawa', 'mati', 'terima', 'buat', 'keburu', 'bawa', 'mati', 'baik', 'orang', 'bawa', 'baik', 'mati', 'usaha']
['pilih', 'sehat', 'buka', 'judul', 'jujur', 'adil', 'sosok', 'pimpin', 'pilih', 'masyarakat', 'transparan', 'diviralkan', 'publik', 'harap', 'm

In [18]:
join=[]
for i in range(len(stemming)):
  joinkata = ' '.join(stemming[i])
  join.append(joinkata)

hasilpreproses = pd.DataFrame(join, columns=['Preprocessing'])
hasilpreproses

Preprocessing
0   biar bilang curang biar bukti fakta ini jujur ...
1   pilih sehat buka judul jujur adil sosok pimpin...
2   orang indonesia sabang merauke tutup calon pre...
3   orang calon presiden indonesia kayak caleg dpr...
4   poros mayor ahy anas urbaningrum ibas andi mal...
5   menangx anda prabowo pasang anis kalah cawapre...
6   ya usaha pasang capres menang ganjar pasang an...
7                                           mahfud md
8                            anies amp erick sempurna
9   media amat bodoh bohong dagel politik kuasa kr...
10  masuk nkri sabang meraoke cawapres indonesia t...
11  moga presiden sedekah harta masyarakat butuh u...
12                              mahfud ahok indpenden
13  tgb surve percaya memg nyata safari aji kmna r...
14  tuju capres cawapres pilih rakyat biar berjln ...
15     ya poros apa prabowo setia bendera merah putih
16                        ujung ujung poross maksimal
17            maju pilpres poros logistik pilpres bro
18                        anis rk nasdem pks demokrat
19     anies rasyid baswedan agus harimurti yudhoyono
20  senang yohanes gagal nyapres pilpres aman dama...
21                         golkar berani mandiri ekor
22                                               gprk
23  aerlangga cak imin vs prabowo erik vs ganjar s...
24  biar pelangar ham berat pimpin negriii korupto...
25  aniss sang satrioo paningit bawa kemakmutan ja...
26                                satrio pingit yaman
27                                            bos men
28                   inti rakyat butuh annis baswedan
29                                                   
30        rakyat adil golong rakyat ubah cebong takut
31                                         rakyat bro
32  poros poros menang anda tum partai calon ahok ...
33  prasetyo insani agama penting politik agama ku...
34                                       ahoknya ogah
35              turahan bayar lembaga survey nya ogah
36          ahok bayar lembaga survey kali bayar tuju
37        turahan lembaga survey pikir nama ahok list
38  pusing calon anies baswedan ganjar pranowo pra...
39                                  ujung ujung poros
40            apa partai nasdem perintah partai gurem
41  poros koalisi ubah bubar koalisi prabowo bentu...
42                                              poros
43  golkar jadi poros ridwan kamil erick thohir bi...
44  tuju ayo bikin poros ridwan kamil eric thohir ...
45                          bond biar seru kalo poros
46  usung erik pasang prabowo golkar koalisi pkb u...
47               inspirator negeri pilpres aman sejuk
48  iya hehe ayo bikin poros dukung ridwan kamil m...
49       ppp susul hanura suara hilang parlemen usung
50  poros peluang koalisi habis koalisi bubar opos...
51                                        bador parah
52                               turahan budak partai
53       biar presiden republik indonesa tugas partai
54  capres cawapres lingkar jkw gub palestina wowo...
55  ngaruh opi untunge awak entar tukang ngathong ...
56                              iya orang buzzer anis

## TF-IDF

In [19]:
tr_model  = TfidfVectorizer()
tf_vector = tr_model.fit_transform(hasilpreproses['Preprocessing'])

In [20]:
tf_array = tf_vector.toarray()
print(tf_array)

[[0.05704535 0.         0.         ... 0.         0.         0.        ]
 [0.07516615 0.         0.         ... 0.         0.         0.        ]
 [0.05612959 0.         0.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]]


In [21]:
words_set = tr_model.get_feature_names_out()
print(words_set)

['adil' 'aerlangga' 'agama' 'agus' 'aher' 'ahok' 'ahoknya' 'ahy'
 'airlangga' 'ajak' 'ajar' 'aji' 'aju' 'akal' 'akbar' 'akibat' 'allah'
 'alumni' 'aman' 'amanah' 'amat' 'ambisi' 'amp' 'anas' 'anda' 'andi'
 'anggota' 'anies' 'anis' 'aniss' 'annis' 'apa' 'awak' 'ayo' 'ayom' 'baca'
 'back' 'bador' 'baik' 'bangsa' 'bangun' 'banyak' 'barat' 'baswedan'
 'batas' 'bawa' 'bawaslunya' 'bayar' 'beda' 'belaka' 'belanda' 'beliau'
 'bendera' 'bentuk' 'ber' 'berani' 'berat' 'berba' 'berjln' 'besar' 'biar'
 'bijaksana' 'bikin' 'bilang' 'bin' 'bingung' 'biyar' 'black' 'bodoh'
 'bohong' 'bola' 'bond' 'bos' 'bro' 'buang' 'buat' 'bubar' 'budak' 'buka'
 'bukti' 'buru' 'buruk' 'butuh' 'buzzer' 'cak' 'caleg' 'calon' 'calonin'
 'capres' 'cawapres' 'cebong' 'ceramah' 'cerita' 'cinta' 'cipta' 'coba'
 'coblos' 'cocok' 'contoh' 'copet' 'cuman' 'curang' 'daerah' 'dagel'
 'dalil' 'damai' 'dampak' 'dapat' 'darah' 'daulat' 'daya' 'demo'
 'demokrasi' 'demokrat' 'dengar' 'depan' 'desa' 'dgan' 'dicapreskan'
 'dinamika' 

In [22]:
df = pd.DataFrame(tf_array, columns = words_set)
df

adil  aerlangga     agama      agus      aher      ahok   ahoknya  \
0   0.057045   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
1   0.075166   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
2   0.056130   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
3   0.000000   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
4   0.000000   0.000000  0.000000  0.000000  0.343159  0.000000  0.000000   
5   0.000000   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
6   0.000000   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
7   0.000000   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
8   0.000000   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
9   0.000000   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
10  0.000000   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
11  0.000000   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
12  0.000000   0.000000  0.000000  0.000000  0.000000  0.517432  0.000000   
13  0.000000   0.000000  0.148714  0.000000  0.000000  0.000000  0.000000   
14  0.174640   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
15  0.000000   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
16  0.000000   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
17  0.000000   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
18  0.000000   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
19  0.000000   0.000000  0.000000  0.437841  0.000000  0.000000  0.000000   
20  0.000000   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
21  0.000000   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
22  0.000000   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
23  0.000000   0.247065  0.000000  0.000000  0.000000  0.000000  0.000000   
24  0.000000   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
25  0.000000   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
26  0.000000   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
27  0.000000   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
28  0.000000   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
29  0.000000   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
30  0.309101   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
31  0.000000   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
32  0.000000   0.000000  0.000000  0.000000  0.000000  0.386179  0.000000   
33  0.000000   0.000000  0.565560  0.000000  0.000000  0.000000  0.000000   
34  0.000000   0.000000  0.000000  0.000000  0.000000  0.000000  0.740652   
35  0.000000   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
36  0.000000   0.000000  0.000000  0.000000  0.000000  0.312310  0.000000   
37  0.000000   0.000000  0.000000  0.000000  0.000000  0.334796  0.000000   
38  0.000000   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
39  0.000000   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
40  0.000000   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
41  0.000000   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
42  0.000000   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
43  0.000000   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
44  0.000000   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
45  0.000000   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
46  0.000000   0.163835  0.000000  0.000000  0.000000  0.000000  0.000000   
47  0.000000   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
48  0.000000   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
49  0.000000   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
50  0.000000   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
51  

## Singular Value Decomposition

Teknik untuk mendekomposisi matriks berukuran apa saja (biasanya diaplikasikan untuk matriks dengan ukuran sangat besar), untuk mempermudah pengolahan data.

In [23]:
from sklearn.decomposition import TruncatedSVD
lsa_model = TruncatedSVD(n_components=3, algorithm='randomized', n_iter=10, random_state=42)
lsa_top=lsa_model.fit_transform(df)

In [24]:
print(lsa_top)
print(lsa_top.shape)  # (no_of_doc*no_of_topics)

[[ 2.81190505e-01 -3.30850275e-02 -2.05019680e-01]
 [ 2.78595398e-01 -1.02924001e-01 -2.61699976e-01]
 [ 2.35966017e-01 -1.15246951e-01 -1.65546896e-01]
 [ 1.93258490e-01 -1.04598788e-01 -1.69483043e-01]
 [ 1.88169844e-01  1.57348415e-01  6.55905820e-02]
 [ 1.88359614e-01 -5.83269059e-02 -1.37587588e-02]
 [ 2.40045764e-01  2.45880166e-03 -5.09663137e-02]
 [ 3.99451002e-02 -8.35941071e-02  6.05501899e-02]
 [ 1.27122634e-01  3.27460991e-02 -4.34840987e-02]
 [ 1.41936854e-01 -8.71120912e-02 -5.78759673e-02]
 [ 9.72195954e-02 -5.64549875e-02 -6.27332011e-02]
 [ 2.00113843e-01 -1.41290478e-01 -2.43308811e-01]
 [ 1.20009921e-01 -2.24534915e-01  1.81664625e-01]
 [ 8.46748894e-02 -1.16645995e-01  2.85199827e-02]
 [ 3.61892781e-01 -1.57208931e-01 -2.76120853e-01]
 [ 2.16956761e-01  1.55693938e-01  7.29893055e-02]
 [ 1.78978426e-01  3.90241131e-01  2.74733385e-01]
 [ 2.68774011e-01  1.85996831e-01  6.66431419e-03]
 [ 9.40334016e-02 -1.76007551e-02 -5.18315659e-03]
 [ 8.97142184e-02 -3.25902953e-

In [25]:
#bobot setiap topik terhadap dokumen
dt = pd.DataFrame(lsa_top, columns=['topik1','topik2','topik3'])
dt

topik1    topik2    topik3
0   0.281191 -0.033085 -0.205020
1   0.278595 -0.102924 -0.261700
2   0.235966 -0.115247 -0.165547
3   0.193258 -0.104599 -0.169483
4   0.188170  0.157348  0.065591
5   0.188360 -0.058327 -0.013759
6   0.240046  0.002459 -0.050966
7   0.039945 -0.083594  0.060550
8   0.127123  0.032746 -0.043484
9   0.141937 -0.087112 -0.057876
10  0.097220 -0.056455 -0.062733
11  0.200114 -0.141290 -0.243309
12  0.120010 -0.224535  0.181665
13  0.084675 -0.116646  0.028520
14  0.361893 -0.157209 -0.276121
15  0.216957  0.155694  0.072989
16  0.178978  0.390241  0.274733
17  0.268774  0.185997  0.006664
18  0.094033 -0.017601 -0.005183
19  0.089714 -0.032590 -0.090776
20  0.104820  0.031486 -0.051485
21  0.075702  0.006428 -0.025532
22  0.000029  0.000043  0.000074
23  0.215884 -0.028160 -0.043077
24  0.088285 -0.015580 -0.067648
25  0.082331 -0.041169 -0.064803
26  0.000038  0.000434 -0.001181
27  0.000021 -0.000048 -0.000824
28  0.170570 -0.139893 -0.225676
29  0.000000  0.000000  0.000000
30  0.222400 -0.148816 -0.236170
31  0.242719 -0.119462 -0.227220
32  0.542487 -0.338690 -0.052537
33  0.034271 -0.011138  0.004282
34  0.027752 -0.113000  0.180623
35  0.158062 -0.437328  0.628400
36  0.182251 -0.419804  0.522979
37  0.157453 -0.428052  0.518267
38  0.334329 -0.150746 -0.290882
39  0.326823  0.539719  0.339843
40  0.211962 -0.193664  0.041975
41  0.301881  0.223871  0.093732
42  0.416906  0.450645  0.208989
43  0.349271  0.203044 -0.007122
44  0.274758  0.169223  0.057958
45  0.296454  0.205744  0.033118
46  0.295848  0.081428  0.036321
47  0.068506  0.055664 -0.010766
48  0.356639  0.076231 -0.100967
49  0.039363 -0.001214 -0.006084
50  0.307753  0.328654  0.256315
51  0.000011  0.000397 -0.000626
52  0.192777 -0.308943  0.232369
53  0.282889 -0.191039 -0.080382
54  0.147445 -0.071860 -0.126049
55  0.000007  0.000099 -0.000773
56  0.122557 -0.010991 -0.063547

In [67]:
SV = lsa_model.components_
print(SV)
print(SV.shape)#(no_of_topics*no_of_words)

[[ 6.83634352e-02  3.82132325e-02  1.19948530e-02 ...  2.18894679e-05
   1.57205093e-02  1.47330856e-02]
 [-4.25451009e-02  3.03531603e-03 -1.12935403e-02 ...  2.50621616e-04
   6.06099228e-03 -6.52467695e-03]
 [-8.06941096e-02 -2.31546882e-03  3.41902995e-03 ... -6.81907890e-04
  -1.03046367e-02 -1.96711358e-02]]
(3, 489)


In [74]:
#bobot kata/topik

label = []
for i in range(1,490):
    masukan = f"kata ke-{i}"
    label.append(masukan)
topik = pd.DataFrame(SV, columns=label)
topik.rename(index={0: "topik1", 1: "topik2", 2: "topik3"})

kata ke-1  kata ke-2  kata ke-3  kata ke-4  kata ke-5  kata ke-6  \
topik1   0.068363   0.038213   0.011995   0.014733   0.024228   0.143072   
topik2  -0.042545   0.003035  -0.011294  -0.006525   0.025343  -0.245941   
topik3  -0.080694  -0.002315   0.003419  -0.019671   0.011346   0.204799   

        kata ke-7  kata ke-8  kata ke-9  kata ke-10  ...  kata ke-480  \
topik1   0.007730   0.078032   0.055047    0.016085  ...     0.008043   
topik2  -0.039131   0.033331  -0.031886   -0.002389  ...    -0.001195   
topik3   0.066120   0.014251  -0.063279   -0.015593  ...    -0.007797   

        kata ke-481  kata ke-482  kata ke-483  kata ke-484  kata ke-485  \
topik1     0.105194     0.002603     0.006642     0.003321     0.016796   
topik2    -0.045296    -0.004545    -0.004057    -0.002028    -0.010448   
topik3    -0.021522     0.001210    -0.006191    -0.003096    -0.019021   

        kata ke-486  kata ke-487  kata ke-488  kata ke-489  
topik1     0.047452     0.000022     0.015721     0.014733  
topik2     0.026676     0.000251     0.006061    -0.006525  
topik3     0.008236    -0.000682    -0.010305    -0.019671  

[3 rows x 489 columns]